/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.dodaj;

import domen.Osoba;
import domen.Zaposleni;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Igor
 */
public class FormaDodajIznajmljivanje extends javax.swing.JFrame {

    /**
     * Creates new form FormaDodajIznajmljivanje
     */
    public FormaDodajIznajmljivanje() {
        initComponents();
        this.setLocationRelativeTo(null);
        pack();
        setResizable(true);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUkupnoSati = new javax.swing.JLabel();
        jLabelUkupanIznos = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jComboBoxOsoba = new javax.swing.JComboBox<>();
        jTextFieldDatumIznajmljivanja = new javax.swing.JTextField();
        jTextFieldUkupnoSati = new javax.swing.JTextField();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCenaPoSatu = new javax.swing.JLabel();
        jLabelOprema = new javax.swing.JLabel();
        jComboBoxOprema = new javax.swing.JComboBox<>();
        jComboBoxTipOpreme = new javax.swing.JComboBox<>();
        jLabelTipOpreme = new javax.swing.JLabel();
        jTextFieldCenaPoSatu = new javax.swing.JTextField();
        jLabelBrojSati = new javax.swing.JLabel();
        jTextFieldBrojSati = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxNacinPlacanja = new javax.swing.JComboBox<>();
        jLabelDatumPovratkaOpreme = new javax.swing.JLabel();
        jTextFieldDatumPovratkaOpreme = new javax.swing.JTextField();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();
        jLabelCena = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeIznajmljivanja = new javax.swing.JTable();
        jButtonAzurirajStavku = new javax.swing.JButton();
        jButtonPotvrdiAzuriranje = new javax.swing.JButton();
        jButtonKreirajRacun = new javax.swing.JButton();
        jButtonObrisiIznajmljivanje = new javax.swing.JButton();
        jButtonOmoguciIzmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zaposleni");

        jLabel2.setText("Osoba");

        jLabel3.setText("Datum iznajmljivanja");

        jLabelUkupnoSati.setText("Ukupno sati");

        jLabelUkupanIznos.setText("Ukupan iznos");

        jLabelCenaPoSatu.setText("Cena po satu");

        jLabelOprema.setText("Oprema");

        jLabelTipOpreme.setText("Tip opreme");

        jLabelBrojSati.setText("Broj sati");

        jLabel10.setText("Nacin placanja");

        jComboBoxNacinPlacanja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gotovina", "Kartica" }));
        jComboBoxNacinPlacanja.setSelectedIndex(-1);

        jLabelDatumPovratkaOpreme.setText("Datum povratka opreme");

        jButtonDodajStavku.setText("Kreiraj stavku");

        jButtonDodaj.setText("Zapamti iznajmljivanje");

        jButtonAzuriraj.setText("Izmeni iznajmljivanje");

        jLabelCena.setText("Cena");

        jTableStavkeIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeIznajmljivanja);

        jButtonAzurirajStavku.setText("Izmeni stavku");

        jButtonPotvrdiAzuriranje.setText("Potvrdi azuriranje");

        jButtonKreirajRacun.setText("Kreiraj iznajmljivanje");

        jButtonObrisiIznajmljivanje.setText("Obrisi iznajmljivanje");

        jButtonOmoguciIzmenu.setText("Omoguci izmenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUkupanIznos)
                                .addGap(72, 72, 72)
                                .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUkupnoSati)
                                .addGap(80, 80, 80)
                                .addComponent(jTextFieldUkupnoSati, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(237, 237, 237)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDodaj)
                            .addComponent(jButtonObrisiIznajmljivanje)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109)
                        .addComponent(jComboBoxOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldDatumIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10)
                        .addGap(64, 64, 64)
                        .addComponent(jComboBoxNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOmoguciIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonKreirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelOprema)
                        .addGap(84, 84, 84)
                        .addComponent(jComboBoxOprema, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelTipOpreme)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelCenaPoSatu)
                        .addGap(58, 58, 58)
                        .addComponent(jTextFieldCenaPoSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelCena)
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelBrojSati)
                        .addGap(85, 85, 85)
                        .addComponent(jTextFieldBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelDatumPovratkaOpreme)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldDatumPovratkaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonAzurirajStavku))
                            .addComponent(jButtonPotvrdiAzuriranje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jButtonDodajStavku))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jTextFieldDatumIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jButtonOmoguciIzmenu)
                            .addComponent(jButtonKreirajRacun))))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOprema)
                            .addComponent(jLabelTipOpreme))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelCenaPoSatu))
                    .addComponent(jTextFieldCenaPoSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelCena))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelBrojSati))
                    .addComponent(jTextFieldBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDatumPovratkaOpreme))
                    .addComponent(jTextFieldDatumPovratkaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAzurirajStavku)
                            .addComponent(jButtonPotvrdiAzuriranje)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButtonDodajStavku)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUkupnoSati))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUkupnoSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonObrisiIznajmljivanje)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelUkupanIznos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAzuriraj)
                    .addComponent(jButtonDodaj))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonAzuriraj() {
        return jButtonAzuriraj;
    }

    public void setjButtonAzuriraj(JButton jButtonAzuriraj) {
        this.jButtonAzuriraj = jButtonAzuriraj;
    }

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    public JButton getjButtonDodajStavku() {
        return jButtonDodajStavku;
    }

    public void setjButtonDodajStavku(JButton jButtonDodajStavku) {
        this.jButtonDodajStavku = jButtonDodajStavku;
    }

    public JTable getjTableStavkeIznajmljivanja() {
        return jTableStavkeIznajmljivanja;
    }

    public void setjTableStavkeIznajmljivanja(JTable jTableStavkeIznajmljivanja) {
        this.jTableStavkeIznajmljivanja = jTableStavkeIznajmljivanja;
    }

    public JComboBox<String> getjComboBoxNacinPlacanja() {
        return jComboBoxNacinPlacanja;
    }

    public void setjComboBoxNacinPlacanja(JComboBox<String> jComboBoxNacinPlacanja) {
        this.jComboBoxNacinPlacanja = jComboBoxNacinPlacanja;
    }

    public JComboBox<String> getjComboBoxOprema() {
        return jComboBoxOprema;
    }

    public void setjComboBoxOprema(JComboBox<String> jComboBoxOprema) {
        this.jComboBoxOprema = jComboBoxOprema;
    }

    public JComboBox<Osoba> getjComboBoxOsoba() {
        return jComboBoxOsoba;
    }

    public void setjComboBoxOsoba(JComboBox<Osoba> jComboBoxOsoba) {
        this.jComboBoxOsoba = jComboBoxOsoba;
    }

    public JComboBox<String> getjComboBoxTipOpreme() {
        return jComboBoxTipOpreme;
    }

    public void setjComboBoxTipOpreme(JComboBox<String> jComboBoxTipOpreme) {
        this.jComboBoxTipOpreme = jComboBoxTipOpreme;
    }

    public JComboBox<Zaposleni> getjComboBoxZaposleni() {
        return jComboBoxZaposleni;
    }

    public void setjComboBoxZaposleni(JComboBox<Zaposleni> jComboBoxZaposleni) {
        this.jComboBoxZaposleni = jComboBoxZaposleni;
    }

    public JTextField getjTextFieldBrojSati() {
        return jTextFieldBrojSati;
    }

    public void setjTextFieldBrojSati(JTextField jTextFieldBrojSati) {
        this.jTextFieldBrojSati = jTextFieldBrojSati;
    }

    public JTextField getjTextFieldDatumIznajmljivanja() {
        return jTextFieldDatumIznajmljivanja;
    }

    public void setjTextFieldDatumIznajmljivanja(JTextField jTextFieldDatumIznajmljivanja) {
        this.jTextFieldDatumIznajmljivanja = jTextFieldDatumIznajmljivanja;
    }

    public JTextField getjTextFieldDatumPovratkaOpreme() {
        return jTextFieldDatumPovratkaOpreme;
    }

    public void setjTextFieldDatumPovratkaOpreme(JTextField jTextFieldDatumPovratkaOpreme) {
        this.jTextFieldDatumPovratkaOpreme = jTextFieldDatumPovratkaOpreme;
    }

    public JTextField getjTextFieldUkupanIznos() {
        return jTextFieldUkupanIznos;
    }

    public void setjTextFieldUkupanIznos(JTextField jTextFieldUkupanIznos) {
        this.jTextFieldUkupanIznos = jTextFieldUkupanIznos;
    }

    public JTextField getjTextFieldCena() {
        return jTextFieldCena;
    }

    public void setjTextFieldCena(JTextField jTextFieldCena) {
        this.jTextFieldCena = jTextFieldCena;
    }

    public JTextField getjTextFieldCenaPoSatu() {
        return jTextFieldCenaPoSatu;
    }

    public void setjTextFieldCenaPoSatu(JTextField jTextFieldCenaPoSatu) {
        this.jTextFieldCenaPoSatu = jTextFieldCenaPoSatu;
    }

    public JTextField getjTextFieldUkupnoSati() {
        return jTextFieldUkupnoSati;
    }

    public void setjTextFieldUkupnoSati(JTextField jTextFieldUkupnoSati) {
        this.jTextFieldUkupnoSati = jTextFieldUkupnoSati;
    }

    public JLabel getjLabelBrojSati() {
        return jLabelBrojSati;
    }

    public void setjLabelBrojSati(JLabel jLabelBrojSati) {
        this.jLabelBrojSati = jLabelBrojSati;
    }

    public JLabel getjLabelCena() {
        return jLabelCena;
    }

    public void setjLabelCena(JLabel jLabelCena) {
        this.jLabelCena = jLabelCena;
    }

    public JLabel getjLabelCenaPoSatu() {
        return jLabelCenaPoSatu;
    }

    public void setjLabelCenaPoSatu(JLabel jLabelCenaPoSatu) {
        this.jLabelCenaPoSatu = jLabelCenaPoSatu;
    }

    public JLabel getjLabelDatumPovratkaOpreme() {
        return jLabelDatumPovratkaOpreme;
    }

    public void setjLabelDatumPovratkaOpreme(JLabel jLabelDatumPovratkaOpreme) {
        this.jLabelDatumPovratkaOpreme = jLabelDatumPovratkaOpreme;
    }

    public JLabel getjLabelOprema() {
        return jLabelOprema;
    }

    public void setjLabelOprema(JLabel jLabelOprema) {
        this.jLabelOprema = jLabelOprema;
    }

    public JLabel getjLabelTipOpreme() {
        return jLabelTipOpreme;
    }

    public void setjLabelTipOpreme(JLabel jLabelTipOpreme) {
        this.jLabelTipOpreme = jLabelTipOpreme;
    }

    public JLabel getjLabelUkupanIznos() {
        return jLabelUkupanIznos;
    }

    public void setjLabelUkupanIznos(JLabel jLabelUkupanIznos) {
        this.jLabelUkupanIznos = jLabelUkupanIznos;
    }

    public JLabel getjLabelUkupnoSati() {
        return jLabelUkupnoSati;
    }

    public void setjLabelUkupnoSati(JLabel jLabelUkupnoSati) {
        this.jLabelUkupnoSati = jLabelUkupnoSati;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JButton getjButtonAzurirajStavku() {
        return jButtonAzurirajStavku;
    }

    public void setjButtonAzurirajStavku(JButton jButtonAzurirajStavku) {
        this.jButtonAzurirajStavku = jButtonAzurirajStavku;
    }

    public JButton getjButtonPotvrdiAzuriranje() {
        return jButtonPotvrdiAzuriranje;
    }

    public void setjButtonPotvrdiAzuriranje(JButton jButtonPotvrdiAzuriranje) {
        this.jButtonPotvrdiAzuriranje = jButtonPotvrdiAzuriranje;
    }

    public JButton getjButtonKreirajRacun() {
        return jButtonKreirajRacun;
    }

    public void setjButtonKreirajRacun(JButton jButtonKreirajRacun) {
        this.jButtonKreirajRacun = jButtonKreirajRacun;
    }

    public JButton getjButtonObrisiIznajmljivanje() {
        return jButtonObrisiIznajmljivanje;
    }

    public void setjButtonObrisiIznajmljivanje(JButton jButtonObrisiIznajmljivanje) {
        this.jButtonObrisiIznajmljivanje = jButtonObrisiIznajmljivanje;
    }

    public JButton getjButtonOmoguciIzmenu() {
        return jButtonOmoguciIzmenu;
    }

    public void setjButtonOmoguciIzmenu(JButton jButtonOmoguciIzmenu) {
        this.jButtonOmoguciIzmenu = jButtonOmoguciIzmenu;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonAzurirajStavku;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonKreirajRacun;
    private javax.swing.JButton jButtonObrisiIznajmljivanje;
    private javax.swing.JButton jButtonOmoguciIzmenu;
    private javax.swing.JButton jButtonPotvrdiAzuriranje;
    private javax.swing.JComboBox<String> jComboBoxNacinPlacanja;
    private javax.swing.JComboBox<String> jComboBoxOprema;
    private javax.swing.JComboBox<Osoba> jComboBoxOsoba;
    private javax.swing.JComboBox<String> jComboBoxTipOpreme;
    private javax.swing.JComboBox<Zaposleni> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBrojSati;
    private javax.swing.JLabel jLabelCena;
    private javax.swing.JLabel jLabelCenaPoSatu;
    private javax.swing.JLabel jLabelDatumPovratkaOpreme;
    private javax.swing.JLabel jLabelOprema;
    private javax.swing.JLabel jLabelTipOpreme;
    private javax.swing.JLabel jLabelUkupanIznos;
    private javax.swing.JLabel jLabelUkupnoSati;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableStavkeIznajmljivanja;
    private javax.swing.JTextField jTextFieldBrojSati;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldCenaPoSatu;
    private javax.swing.JTextField jTextFieldDatumIznajmljivanja;
    private javax.swing.JTextField jTextFieldDatumPovratkaOpreme;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    private javax.swing.JTextField jTextFieldUkupnoSati;
    // End of variables declaration//GEN-END:variables

    
   public void dodajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
    public void azurirajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        jButtonAzuriraj.addActionListener(actionListener);
    }
    
    public void dodajStavkuAddActionListener(ActionListener actionListener) {
        jButtonDodajStavku.addActionListener(actionListener);
    }
    
    public void azurirajStavkuIznajmljivanjaAddActionListener(ActionListener actionListener){
        jButtonAzurirajStavku.addActionListener(actionListener);
    }
    
    public void potvrdiAzuriranjeStavkeIznajmljivanjaAddActionListener(ActionListener actionListener){
        jButtonPotvrdiAzuriranje.addActionListener(actionListener);
    }
    
    public void kreirajRacunAddActionListener(ActionListener actionListener){
        jButtonKreirajRacun.addActionListener(actionListener);
    }
    
    public void obrisiIznajmljivanjeAddActionListener(ActionListener actionListener){
        jButtonObrisiIznajmljivanje.addActionListener(actionListener);
    }
    
    public void jTableStavkaIznajmljivanjaMouseListener(MouseListener mouseListener) {
        jTableStavkeIznajmljivanja.addMouseListener(mouseListener);
    }
    
    public void omoguciIzmenuAddActionListener(ActionListener actionListener){
        jButtonOmoguciIzmenu.addActionListener(actionListener);
    }

}
