/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Osoba;
import domen.Zaposleni;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Igor
 */
public class FormaDodajIznajmljivanje extends javax.swing.JFrame {

    /**
     * Creates new form FormaDodajIznajmljivanje
     */
    public FormaDodajIznajmljivanje() {
        initComponents();
        pack();
        setResizable(true);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUkupnoSati = new javax.swing.JLabel();
        jLabelUkupanIznos = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jComboBoxOsoba = new javax.swing.JComboBox<>();
        jTextFieldDatumIznajmljivanja = new javax.swing.JTextField();
        jTextFieldUkupnoSati = new javax.swing.JTextField();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCenaPoSatu = new javax.swing.JLabel();
        jLabelOprema = new javax.swing.JLabel();
        jComboBoxOprema = new javax.swing.JComboBox<>();
        jComboBoxTipOpreme = new javax.swing.JComboBox<>();
        jLabelTipOpreme = new javax.swing.JLabel();
        jTextFieldCenaPoSatu = new javax.swing.JTextField();
        jLabelBrojSati = new javax.swing.JLabel();
        jTextFieldBrojSati = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxNacinPlacanja = new javax.swing.JComboBox<>();
        jLabelDatumPovratkaOpreme = new javax.swing.JLabel();
        jTextFieldDatumPovratkaOpreme = new javax.swing.JTextField();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();
        jLabelCena = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeIznajmljivanja = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zaposleni");

        jLabel2.setText("Osoba");

        jLabel3.setText("Datum iznajmljivanja");

        jLabelUkupnoSati.setText("Ukupno sati");

        jLabelUkupanIznos.setText("Ukupan iznos");

        jLabelCenaPoSatu.setText("Cena po satu");

        jLabelOprema.setText("Oprema");

        jLabelTipOpreme.setText("Tip opreme");

        jLabelBrojSati.setText("Broj sati");

        jLabel10.setText("Nacin placanja");

        jComboBoxNacinPlacanja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gotovina", "Kartica" }));
        jComboBoxNacinPlacanja.setSelectedIndex(-1);

        jLabelDatumPovratkaOpreme.setText("Datum povratka opreme");

        jButtonDodajStavku.setText("Dodaj stavku");

        jButtonDodaj.setText("Dodaj");

        jButtonAzuriraj.setText("Azuriraj");

        jLabelCena.setText("Cena");

        jTableStavkeIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeIznajmljivanja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelUkupanIznos)
                                        .addGap(72, 72, 72)
                                        .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelUkupnoSati)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldUkupnoSati, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAzuriraj)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDodaj)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDatumPovratkaOpreme)
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextFieldDatumPovratkaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(195, 195, 195)
                                        .addComponent(jButtonDodajStavku))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelOprema)
                                                .addComponent(jLabelCenaPoSatu)
                                                .addComponent(jLabelBrojSati))
                                            .addGap(58, 58, 58)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBoxOprema, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                                .addComponent(jTextFieldCenaPoSatu, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldBrojSati, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelTipOpreme)
                                                .addComponent(jLabelCena))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBoxTipOpreme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 57, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jComboBoxNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxZaposleni, 0, 158, Short.MAX_VALUE)
                                    .addComponent(jComboBoxOsoba, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDatumIznajmljivanja))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDatumIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOprema)
                    .addComponent(jComboBoxOprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipOpreme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCenaPoSatu)
                            .addComponent(jTextFieldCenaPoSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCena)
                            .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrojSati)
                    .addComponent(jTextFieldBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatumPovratkaOpreme)
                    .addComponent(jTextFieldDatumPovratkaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajStavku))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUkupnoSati)
                    .addComponent(jTextFieldUkupnoSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUkupanIznos)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonAzuriraj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonAzuriraj() {
        return jButtonAzuriraj;
    }

    public void setjButtonAzuriraj(JButton jButtonAzuriraj) {
        this.jButtonAzuriraj = jButtonAzuriraj;
    }

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    public JButton getjButtonDodajStavku() {
        return jButtonDodajStavku;
    }

    public void setjButtonDodajStavku(JButton jButtonDodajStavku) {
        this.jButtonDodajStavku = jButtonDodajStavku;
    }

    public JTable getjTableStavkeIznajmljivanja() {
        return jTableStavkeIznajmljivanja;
    }

    public void setjTableStavkeIznajmljivanja(JTable jTableStavkeIznajmljivanja) {
        this.jTableStavkeIznajmljivanja = jTableStavkeIznajmljivanja;
    }

    public JComboBox<String> getjComboBoxNacinPlacanja() {
        return jComboBoxNacinPlacanja;
    }

    public void setjComboBoxNacinPlacanja(JComboBox<String> jComboBoxNacinPlacanja) {
        this.jComboBoxNacinPlacanja = jComboBoxNacinPlacanja;
    }

    public JComboBox<String> getjComboBoxOprema() {
        return jComboBoxOprema;
    }

    public void setjComboBoxOprema(JComboBox<String> jComboBoxOprema) {
        this.jComboBoxOprema = jComboBoxOprema;
    }

    public JComboBox<Osoba> getjComboBoxOsoba() {
        return jComboBoxOsoba;
    }

    public void setjComboBoxOsoba(JComboBox<Osoba> jComboBoxOsoba) {
        this.jComboBoxOsoba = jComboBoxOsoba;
    }

    public JComboBox<String> getjComboBoxTipOpreme() {
        return jComboBoxTipOpreme;
    }

    public void setjComboBoxTipOpreme(JComboBox<String> jComboBoxTipOpreme) {
        this.jComboBoxTipOpreme = jComboBoxTipOpreme;
    }

    public JComboBox<Zaposleni> getjComboBoxZaposleni() {
        return jComboBoxZaposleni;
    }

    public void setjComboBoxZaposleni(JComboBox<Zaposleni> jComboBoxZaposleni) {
        this.jComboBoxZaposleni = jComboBoxZaposleni;
    }

    public JTextField getjTextFieldBrojSati() {
        return jTextFieldBrojSati;
    }

    public void setjTextFieldBrojSati(JTextField jTextFieldBrojSati) {
        this.jTextFieldBrojSati = jTextFieldBrojSati;
    }

    public JTextField getjTextFieldDatumIznajmljivanja() {
        return jTextFieldDatumIznajmljivanja;
    }

    public void setjTextFieldDatumIznajmljivanja(JTextField jTextFieldDatumIznajmljivanja) {
        this.jTextFieldDatumIznajmljivanja = jTextFieldDatumIznajmljivanja;
    }

    public JTextField getjTextFieldDatumPovratkaOpreme() {
        return jTextFieldDatumPovratkaOpreme;
    }

    public void setjTextFieldDatumPovratkaOpreme(JTextField jTextFieldDatumPovratkaOpreme) {
        this.jTextFieldDatumPovratkaOpreme = jTextFieldDatumPovratkaOpreme;
    }

    public JTextField getjTextFieldUkupanIznos() {
        return jTextFieldUkupanIznos;
    }

    public void setjTextFieldUkupanIznos(JTextField jTextFieldUkupanIznos) {
        this.jTextFieldUkupanIznos = jTextFieldUkupanIznos;
    }

    public JTextField getjTextFieldCena() {
        return jTextFieldCena;
    }

    public void setjTextFieldCena(JTextField jTextFieldCena) {
        this.jTextFieldCena = jTextFieldCena;
    }

    public JTextField getjTextFieldCenaPoSatu() {
        return jTextFieldCenaPoSatu;
    }

    public void setjTextFieldCenaPoSatu(JTextField jTextFieldCenaPoSatu) {
        this.jTextFieldCenaPoSatu = jTextFieldCenaPoSatu;
    }

    public JTextField getjTextFieldUkupnoSati() {
        return jTextFieldUkupnoSati;
    }

    public void setjTextFieldUkupnoSati(JTextField jTextFieldUkupnoSati) {
        this.jTextFieldUkupnoSati = jTextFieldUkupnoSati;
    }

    public JLabel getjLabelBrojSati() {
        return jLabelBrojSati;
    }

    public void setjLabelBrojSati(JLabel jLabelBrojSati) {
        this.jLabelBrojSati = jLabelBrojSati;
    }

    public JLabel getjLabelCena() {
        return jLabelCena;
    }

    public void setjLabelCena(JLabel jLabelCena) {
        this.jLabelCena = jLabelCena;
    }

    public JLabel getjLabelCenaPoSatu() {
        return jLabelCenaPoSatu;
    }

    public void setjLabelCenaPoSatu(JLabel jLabelCenaPoSatu) {
        this.jLabelCenaPoSatu = jLabelCenaPoSatu;
    }

    public JLabel getjLabelDatumPovratkaOpreme() {
        return jLabelDatumPovratkaOpreme;
    }

    public void setjLabelDatumPovratkaOpreme(JLabel jLabelDatumPovratkaOpreme) {
        this.jLabelDatumPovratkaOpreme = jLabelDatumPovratkaOpreme;
    }

    public JLabel getjLabelOprema() {
        return jLabelOprema;
    }

    public void setjLabelOprema(JLabel jLabelOprema) {
        this.jLabelOprema = jLabelOprema;
    }

    public JLabel getjLabelTipOpreme() {
        return jLabelTipOpreme;
    }

    public void setjLabelTipOpreme(JLabel jLabelTipOpreme) {
        this.jLabelTipOpreme = jLabelTipOpreme;
    }

    public JLabel getjLabelUkupanIznos() {
        return jLabelUkupanIznos;
    }

    public void setjLabelUkupanIznos(JLabel jLabelUkupanIznos) {
        this.jLabelUkupanIznos = jLabelUkupanIznos;
    }

    public JLabel getjLabelUkupnoSati() {
        return jLabelUkupnoSati;
    }

    public void setjLabelUkupnoSati(JLabel jLabelUkupnoSati) {
        this.jLabelUkupnoSati = jLabelUkupnoSati;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JComboBox<String> jComboBoxNacinPlacanja;
    private javax.swing.JComboBox<String> jComboBoxOprema;
    private javax.swing.JComboBox<Osoba> jComboBoxOsoba;
    private javax.swing.JComboBox<String> jComboBoxTipOpreme;
    private javax.swing.JComboBox<Zaposleni> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBrojSati;
    private javax.swing.JLabel jLabelCena;
    private javax.swing.JLabel jLabelCenaPoSatu;
    private javax.swing.JLabel jLabelDatumPovratkaOpreme;
    private javax.swing.JLabel jLabelOprema;
    private javax.swing.JLabel jLabelTipOpreme;
    private javax.swing.JLabel jLabelUkupanIznos;
    private javax.swing.JLabel jLabelUkupnoSati;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableStavkeIznajmljivanja;
    private javax.swing.JTextField jTextFieldBrojSati;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldCenaPoSatu;
    private javax.swing.JTextField jTextFieldDatumIznajmljivanja;
    private javax.swing.JTextField jTextFieldDatumPovratkaOpreme;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    private javax.swing.JTextField jTextFieldUkupnoSati;
    // End of variables declaration//GEN-END:variables

    
   public void dodajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
    public void azurirajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        jButtonAzuriraj.addActionListener(actionListener);
    }
    
    public void dodajStavkuAddActionListener(ActionListener actionListener) {
        jButtonDodajStavku.addActionListener(actionListener);
    }

}
