/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Zaposleni;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FormaDodajTerminZaposlenog extends javax.swing.JFrame {

    /**
     * Creates new form FormaTerminZaposlenog
     */
    public FormaDodajTerminZaposlenog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelZaposleni = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jLabelTermin = new javax.swing.JLabel();
        jLabelVreme = new javax.swing.JLabel();
        jComboBoxVreme = new javax.swing.JComboBox<>();
        jLabelDatumRada = new javax.swing.JLabel();
        jTextFieldDatumRada = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();
        jComboBoxTermin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelZaposleni.setText("Zaposleni");

        jLabelTermin.setText("Termin");

        jLabelVreme.setText("Vreme");

        jLabelDatumRada.setText("Datum rada");

        jButtonDodaj.setText("Dodaj");

        jButtonAzuriraj.setText("Azuriraj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDatumRada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDatumRada, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelZaposleni)
                            .addComponent(jLabelTermin))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxZaposleni, 0, 113, Short.MAX_VALUE)
                            .addComponent(jComboBoxTermin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabelVreme)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAzuriraj)
                .addGap(18, 18, 18)
                .addComponent(jButtonDodaj)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumRada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatumRada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZaposleni)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTermin)
                    .addComponent(jLabelVreme)
                    .addComponent(jComboBoxVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonAzuriraj))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonAzuriraj() {
        return jButtonAzuriraj;
    }

    public void setjButtonAzuriraj(JButton jButtonAzuriraj) {
        this.jButtonAzuriraj = jButtonAzuriraj;
    }

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    public JComboBox<String> getjComboBoxVreme() {
        return jComboBoxVreme;
    }

    public void setjComboBoxVreme(JComboBox<String> jComboBoxVreme) {
        this.jComboBoxVreme = jComboBoxVreme;
    }

    public JComboBox<Zaposleni> getjComboBoxZaposleni() {
        return jComboBoxZaposleni;
    }

    public void setjComboBoxZaposleni(JComboBox<Zaposleni> jComboBoxZaposleni) {
        this.jComboBoxZaposleni = jComboBoxZaposleni;
    }

    public JLabel getjLabelDatumRada() {
        return jLabelDatumRada;
    }

    public void setjLabelDatumRada(JLabel jLabelDatumRada) {
        this.jLabelDatumRada = jLabelDatumRada;
    }

    public JLabel getjLabelTermin() {
        return jLabelTermin;
    }

    public void setjLabelTermin(JLabel jLabelTermin) {
        this.jLabelTermin = jLabelTermin;
    }

    public JLabel getjLabelVreme() {
        return jLabelVreme;
    }

    public void setjLabelVreme(JLabel jLabelVreme) {
        this.jLabelVreme = jLabelVreme;
    }

    public JLabel getjLabelZaposleni() {
        return jLabelZaposleni;
    }

    public void setjLabelZaposleni(JLabel jLabelZaposleni) {
        this.jLabelZaposleni = jLabelZaposleni;
    }

    public JTextField getjTextFieldDatumRada() {
        return jTextFieldDatumRada;
    }

    public void setjTextFieldDatumRada(JTextField jTextFieldDatumRada) {
        this.jTextFieldDatumRada = jTextFieldDatumRada;
    }

    public JComboBox<String> getjComboBoxTermin() {
        return jComboBoxTermin;
    }

    public void setjComboBoxTermin(JComboBox<String> jComboBoxTermin) {
        this.jComboBoxTermin = jComboBoxTermin;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JComboBox<String> jComboBoxTermin;
    private javax.swing.JComboBox<String> jComboBoxVreme;
    private javax.swing.JComboBox<Zaposleni> jComboBoxZaposleni;
    private javax.swing.JLabel jLabelDatumRada;
    private javax.swing.JLabel jLabelTermin;
    private javax.swing.JLabel jLabelVreme;
    private javax.swing.JLabel jLabelZaposleni;
    private javax.swing.JTextField jTextFieldDatumRada;
    // End of variables declaration//GEN-END:variables

    public void dodajTerminZaposlenogAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
    public void azurirajTerminZaposlenogAddActionListener(ActionListener actionListener) {
        jButtonAzuriraj.addActionListener(actionListener);
    }
    
}
