/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FormaDodajTerminDezurstva extends javax.swing.JFrame {

    /**
     * Creates new form FormaDodajSmenuZaposlenog
     */
    public FormaDodajTerminDezurstva() {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDodaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonPrvaSmena = new javax.swing.JRadioButton();
        jRadioButtonDrugaSmena = new javax.swing.JRadioButton();
        jRadioButtonMedjusmena = new javax.swing.JRadioButton();
        jTextFieldVremeOd = new javax.swing.JTextField();
        jTextFieldVremeDo = new javax.swing.JTextField();
        jLabelSmena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Vreme od");

        jLabel3.setText("Vreme do");

        jButtonDodaj.setText("Dodaj");

        jLabel4.setText("Odaberite tip smene:");

        jRadioButtonPrvaSmena.setText("Prva smena");

        jRadioButtonDrugaSmena.setText("Druga smena");

        jRadioButtonMedjusmena.setText("Medjusmena");

        jTextFieldVremeOd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVremeOdActionPerformed(evt);
            }
        });

        jLabelSmena.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldVremeDo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldVremeOd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonPrvaSmena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDrugaSmena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMedjusmena)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jButtonDodaj)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPrvaSmena)
                    .addComponent(jRadioButtonDrugaSmena)
                    .addComponent(jRadioButtonMedjusmena))
                .addGap(18, 18, 18)
                .addComponent(jLabelSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldVremeOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldVremeDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDodaj)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldVremeOdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVremeOdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVremeOdActionPerformed

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

   

    public JTextField getjTextFieldVremeDo() {
        return jTextFieldVremeDo;
    }

    public void setjTextFieldVremeDo(JTextField jTextFieldVremeDo) {
        this.jTextFieldVremeDo = jTextFieldVremeDo;
    }

    public JTextField getjTextFieldVremeOd() {
        return jTextFieldVremeOd;
    }

    public void setjTextFieldVremeOd(JTextField jTextFieldVremeOd) {
        this.jTextFieldVremeOd = jTextFieldVremeOd;
    }

    public JRadioButton getjRadioButtonDrugaSmena() {
        return jRadioButtonDrugaSmena;
    }

    public void setjRadioButtonDrugaSmena(JRadioButton jRadioButtonDrugaSmena) {
        this.jRadioButtonDrugaSmena = jRadioButtonDrugaSmena;
    }

    public JRadioButton getjRadioButtonMedjusmena() {
        return jRadioButtonMedjusmena;
    }

    public void setjRadioButtonMedjusmena(JRadioButton jRadioButtonMedjusmena) {
        this.jRadioButtonMedjusmena = jRadioButtonMedjusmena;
    }

    public JRadioButton getjRadioButtonPrvaSmena() {
        return jRadioButtonPrvaSmena;
    }

    public void setjRadioButtonPrvaSmena(JRadioButton jRadioButtonPrvaSmena) {
        this.jRadioButtonPrvaSmena = jRadioButtonPrvaSmena;
    }

    public JLabel getjLabelSmena() {
        return jLabelSmena;
    }

    public void setjLabelSmena(JLabel jLabelSmena) {
        this.jLabelSmena = jLabelSmena;
    }

   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSmena;
    private javax.swing.JRadioButton jRadioButtonDrugaSmena;
    private javax.swing.JRadioButton jRadioButtonMedjusmena;
    private javax.swing.JRadioButton jRadioButtonPrvaSmena;
    private javax.swing.JTextField jTextFieldVremeDo;
    private javax.swing.JTextField jTextFieldVremeOd;
    // End of variables declaration//GEN-END:variables
    
    public void dodajTerminDezurstvaAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
}
