/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FormaDodajSkijaskuOpremu extends javax.swing.JFrame {

    /**
     * Creates new form FormaDodajSkijaskuOpremu
     */
    public FormaDodajSkijaskuOpremu() {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNaziv = new javax.swing.JLabel();
        jLabelCenaPoMinutu = new javax.swing.JLabel();
        jLabelTipOpreme = new javax.swing.JLabel();
        jTextFieldCenaPoSatu = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jComboBoxTipSkijaskeOpreme = new javax.swing.JComboBox<>();
        jComboBoxNaziv = new javax.swing.JComboBox<>();
        jButtonAzuriraj = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNaziv.setText("Naziv");

        jLabelCenaPoMinutu.setText("Cena po satu");

        jLabelTipOpreme.setText("Tip opreme");

        jButtonDodaj.setText("Dodaj");

        jComboBoxNaziv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skije", "Snowboard oprema", "Obuca", "Odeca", "Zastitna oprema", "Pribor", "Oprema za odrzavanje" }));
        jComboBoxNaziv.setSelectedIndex(-1);

        jButtonAzuriraj.setText("Azuriraj");

        jLabelID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAzuriraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDodaj)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNaziv)
                    .addComponent(jLabelCenaPoMinutu)
                    .addComponent(jLabelTipOpreme)
                    .addComponent(jLabelID))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCenaPoSatu)
                    .addComponent(jComboBoxTipSkijaskeOpreme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNaziv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldID))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaziv)
                    .addComponent(jComboBoxNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCenaPoMinutu)
                    .addComponent(jTextFieldCenaPoSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipOpreme)
                    .addComponent(jComboBoxTipSkijaskeOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonAzuriraj))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    public JLabel getjLabelCenaPoMinutu() {
        return jLabelCenaPoMinutu;
    }

    public void setjLabelCenaPoMinutu(JLabel jLabelCenaPoMinutu) {
        this.jLabelCenaPoMinutu = jLabelCenaPoMinutu;
    }

    public JLabel getjLabelNaziv() {
        return jLabelNaziv;
    }

    public void setjLabelNaziv(JLabel jLabelNaziv) {
        this.jLabelNaziv = jLabelNaziv;
    }

    public JLabel getjLabelTipOpreme() {
        return jLabelTipOpreme;
    }

    public void setjLabelTipOpreme(JLabel jLabelTipOpreme) {
        this.jLabelTipOpreme = jLabelTipOpreme;
    }

    public JTextField getjTextFieldCenaPoSatu() {
        return jTextFieldCenaPoSatu;
    }

    public void setjTextFieldCenaPoSatu(JTextField jTextFieldCenaPoSatu) {
        this.jTextFieldCenaPoSatu = jTextFieldCenaPoSatu;
    }

    public JComboBox<String> getjComboBoxTipSkijaskeOpreme() {
        return jComboBoxTipSkijaskeOpreme;
    }

    public void setjComboBoxTipSkijaskeOpreme(JComboBox<String> jComboBoxTipSkijaskeOpreme) {
        this.jComboBoxTipSkijaskeOpreme = jComboBoxTipSkijaskeOpreme;
    }

    public JComboBox<String> getjComboBoxNaziv() {
        return jComboBoxNaziv;
    }

    public void setjComboBoxNaziv(JComboBox<String> jComboBoxNaziv) {
        this.jComboBoxNaziv = jComboBoxNaziv;
    }

    public JButton getjButtonAzuriraj() {
        return jButtonAzuriraj;
    }

    public void setjButtonAzuriraj(JButton jButtonAzuriraj) {
        this.jButtonAzuriraj = jButtonAzuriraj;
    }

    public JLabel getjLabelID() {
        return jLabelID;
    }

    public void setjLabelID(JLabel jLabelID) {
        this.jLabelID = jLabelID;
    }

    public JTextField getjTextFieldID() {
        return jTextFieldID;
    }

    public void setjTextFieldID(JTextField jTextFieldID) {
        this.jTextFieldID = jTextFieldID;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JComboBox<String> jComboBoxNaziv;
    private javax.swing.JComboBox<String> jComboBoxTipSkijaskeOpreme;
    private javax.swing.JLabel jLabelCenaPoMinutu;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelTipOpreme;
    private javax.swing.JTextField jTextFieldCenaPoSatu;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables

    public void dodajSkijaskuOpremuAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
    public void azurirajSkijaskuOpremuAddActionListener(ActionListener actionListener) {
        jButtonAzuriraj.addActionListener(actionListener);
    }
    
}
