/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Zaposleni;
import java.io.IOException;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;

/**
 *
 * @author Nikola
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {

        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        Zaposleni ulogovani = cordinator.Cordinator.getInstance().getUlogovani();
        setTitle("Ulogovani korisnik " + ulogovani.getIme() + " " + ulogovani.getPrezime());
        
        
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(jMenuOdjava);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    public JLabel getjLabelNaziv() {
        return jLabelNaziv;
    }

    public void setjLabelNaziv(JLabel jLabelNaziv) {
        this.jLabelNaziv = jLabelNaziv;
    }

    public JMenuItem getjMenuItemOdjaviSe() {
        return jMenuItemOdjaviSe;
    }

    public void setjMenuItemOdjaviSe(JMenuItem jMenuItemOdjaviSe) {
        this.jMenuItemOdjaviSe = jMenuItemOdjaviSe;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelZdravo = new javax.swing.JLabel();
        jLabelNaziv = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemKreirajZaposlenog = new javax.swing.JMenuItem();
        jMenuItemPrikazZaposlenih = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemDodajTerminZaposlenog = new javax.swing.JMenuItem();
        jMenuItemPrikazTerminaZaposlenih = new javax.swing.JMenuItem();
        jMenuOsoba = new javax.swing.JMenu();
        jMenuItemKreirajOsobu = new javax.swing.JMenuItem();
        jMenuItemPregledOsoba = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemKreirajMesto = new javax.swing.JMenuItem();
        jMenuItemPregledMesta = new javax.swing.JMenuItem();
        jMenuIznajmljivanje = new javax.swing.JMenu();
        jMenuItemKreirajIznajmljivanje = new javax.swing.JMenuItem();
        jMenuItemPregledIznajmljivanja = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDodajSkijaskuOpremu = new javax.swing.JMenuItem();
        jMenuItemPregledSkijaskeOpreme = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemKreirajTermin = new javax.swing.JMenuItem();
        jMenuItemPregledTermin = new javax.swing.JMenuItem();
        jMenuOdjava = new javax.swing.JMenu();
        jMenuItemOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelZdravo.setText("Zdravo,");

        jMenu4.setText("Zaposleni");

        jMenuItemKreirajZaposlenog.setText("Kreiraj zaposlenog");
        jMenuItemKreirajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajZaposlenogActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemKreirajZaposlenog);

        jMenuItemPrikazZaposlenih.setText("Prikaz zaposlenih");
        jMenuItemPrikazZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazZaposlenihActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPrikazZaposlenih);

        jMenu5.setText("Termin zaposlenog");

        jMenuItemDodajTerminZaposlenog.setText("Dodaj termin zaposlenog");
        jMenuItemDodajTerminZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTerminZaposlenogActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDodajTerminZaposlenog);

        jMenuItemPrikazTerminaZaposlenih.setText("Prikaz termina zaposlenih");
        jMenuItemPrikazTerminaZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazTerminaZaposlenihActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPrikazTerminaZaposlenih);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        jMenuOsoba.setText("Osoba");

        jMenuItemKreirajOsobu.setText("Kreiraj osobu");
        jMenuItemKreirajOsobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajOsobuActionPerformed(evt);
            }
        });
        jMenuOsoba.add(jMenuItemKreirajOsobu);

        jMenuItemPregledOsoba.setText("Pregled osoba");
        jMenuItemPregledOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledOsobaActionPerformed(evt);
            }
        });
        jMenuOsoba.add(jMenuItemPregledOsoba);

        jMenu1.setText("Mesto");

        jMenuItemKreirajMesto.setText("Kreiraj mesto");
        jMenuItemKreirajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajMestoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemKreirajMesto);

        jMenuItemPregledMesta.setText("Pregled mesta");
        jMenuItemPregledMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledMestaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledMesta);

        jMenuOsoba.add(jMenu1);

        jMenuBar1.add(jMenuOsoba);

        jMenuIznajmljivanje.setText("Iznajmljivanje");

        jMenuItemKreirajIznajmljivanje.setText("Kreiraj iznajmljivanje");
        jMenuItemKreirajIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajIznajmljivanjeActionPerformed(evt);
            }
        });
        jMenuIznajmljivanje.add(jMenuItemKreirajIznajmljivanje);

        jMenuItemPregledIznajmljivanja.setText("Pregled iznajmljivanja");
        jMenuItemPregledIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledIznajmljivanjaActionPerformed(evt);
            }
        });
        jMenuIznajmljivanje.add(jMenuItemPregledIznajmljivanja);

        jMenuBar1.add(jMenuIznajmljivanje);

        jMenu2.setText("Skijaska oprema");

        jMenuItemDodajSkijaskuOpremu.setText("Ubaci skijasku opremu");
        jMenuItemDodajSkijaskuOpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajSkijaskuOpremuActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDodajSkijaskuOpremu);

        jMenuItemPregledSkijaskeOpreme.setText("Pretrazi skijasku opremu");
        jMenuItemPregledSkijaskeOpreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledSkijaskeOpremeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPregledSkijaskeOpreme);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Termin dezurstva");

        jMenuItemKreirajTermin.setText("Ubaci termin dezurstva");
        jMenuItemKreirajTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajTerminActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemKreirajTermin);

        jMenuItemPregledTermin.setText("Pretrazi termin dezurstva");
        jMenuItemPregledTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledTerminActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPregledTermin);

        jMenuBar1.add(jMenu3);

        jMenuOdjava.setText("Odjavi se");
        jMenuOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOdjavaActionPerformed(evt);
            }
        });

        jMenuItemOdjaviSe.setText("Odjavi se");
        jMenuOdjava.add(jMenuItemOdjaviSe);

        jMenuBar1.add(jMenuOdjava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelZdravo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNaziv)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZdravo)
                    .addComponent(jLabelNaziv))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPregledOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledOsobaActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikazOsoba();
    }//GEN-LAST:event_jMenuItemPregledOsobaActionPerformed

    private void jMenuItemKreirajOsobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajOsobuActionPerformed
        cordinator.Cordinator.getInstance().otvoriDodajOsobu();
    }//GEN-LAST:event_jMenuItemKreirajOsobuActionPerformed

    private void jMenuItemPregledIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledIznajmljivanjaActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikazIznajmljivanja();
    }//GEN-LAST:event_jMenuItemPregledIznajmljivanjaActionPerformed

    private void jMenuItemKreirajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajMestoActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajMesto();
    }//GEN-LAST:event_jMenuItemKreirajMestoActionPerformed

    private void jMenuItemPregledMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledMestaActionPerformed
        cordinator.Cordinator.getInstance().otvoriPretraziMesto();
    }//GEN-LAST:event_jMenuItemPregledMestaActionPerformed

    private void jMenuItemDodajSkijaskuOpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajSkijaskuOpremuActionPerformed
        cordinator.Cordinator.getInstance().otvoriFormuDodajSkijaskuOpremu();
    }//GEN-LAST:event_jMenuItemDodajSkijaskuOpremuActionPerformed

    private void jMenuItemPregledSkijaskeOpremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledSkijaskeOpremeActionPerformed
        cordinator.Cordinator.getInstance().otvoriFormuPregledSkijaskeOpreme();
    }//GEN-LAST:event_jMenuItemPregledSkijaskeOpremeActionPerformed

    private void jMenuItemKreirajTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajTerminActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajTerminDezurstva();
    }//GEN-LAST:event_jMenuItemKreirajTerminActionPerformed

    private void jMenuOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOdjavaActionPerformed

    }//GEN-LAST:event_jMenuOdjavaActionPerformed

    private void jMenuItemPregledTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledTerminActionPerformed
        cordinator.Cordinator.getInstance().otvoriPregledTermineDezurstava();
    }//GEN-LAST:event_jMenuItemPregledTerminActionPerformed

    private void jMenuItemPrikazZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazZaposlenihActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikazZaposlenih();
    }//GEN-LAST:event_jMenuItemPrikazZaposlenihActionPerformed

    private void jMenuItemKreirajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajZaposlenogActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajZaposlenog();
    }//GEN-LAST:event_jMenuItemKreirajZaposlenogActionPerformed

    private void jMenuItemDodajTerminZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTerminZaposlenogActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajTerminZaposlenog();
    }//GEN-LAST:event_jMenuItemDodajTerminZaposlenogActionPerformed

    private void jMenuItemPrikazTerminaZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazTerminaZaposlenihActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikazTerminaZaposlenih();
    }//GEN-LAST:event_jMenuItemPrikazTerminaZaposlenihActionPerformed

    private void jMenuItemKreirajIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajIznajmljivanjeActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajIznajmljivanje();
    }//GEN-LAST:event_jMenuItemKreirajIznajmljivanjeActionPerformed

    /**
     *
     * @param args the command line arguments/ public static void main(String
     * args[]) { / Set the Nimbus look and feel
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelZdravo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajSkijaskuOpremu;
    private javax.swing.JMenuItem jMenuItemDodajTerminZaposlenog;
    private javax.swing.JMenuItem jMenuItemKreirajIznajmljivanje;
    private javax.swing.JMenuItem jMenuItemKreirajMesto;
    private javax.swing.JMenuItem jMenuItemKreirajOsobu;
    private javax.swing.JMenuItem jMenuItemKreirajTermin;
    private javax.swing.JMenuItem jMenuItemKreirajZaposlenog;
    private javax.swing.JMenuItem jMenuItemOdjaviSe;
    private javax.swing.JMenuItem jMenuItemPregledIznajmljivanja;
    private javax.swing.JMenuItem jMenuItemPregledMesta;
    private javax.swing.JMenuItem jMenuItemPregledOsoba;
    private javax.swing.JMenuItem jMenuItemPregledSkijaskeOpreme;
    private javax.swing.JMenuItem jMenuItemPregledTermin;
    private javax.swing.JMenuItem jMenuItemPrikazTerminaZaposlenih;
    private javax.swing.JMenuItem jMenuItemPrikazZaposlenih;
    private javax.swing.JMenu jMenuIznajmljivanje;
    private javax.swing.JMenu jMenuOdjava;
    private javax.swing.JMenu jMenuOsoba;
    // End of variables declaration//GEN-END:variables
}
